/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConfirmarEmailRouteImport } from './routes/confirmar-email'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashAnalyticsRouteImport } from './routes/_dash/analytics'
import { Route as DashClientesRouteImport } from './routes/_dash/clientes'
import { Route as DashConfiguracoesRouteImport } from './routes/_dash/configuracoes'
import { Route as DashContaRouteImport } from './routes/_dash/conta'
import { Route as DashDashboardRouteImport } from './routes/_dash/dashboard'
import { Route as DashDominiosRouteImport } from './routes/_dash/dominios'
import { Route as DashEquipeRouteImport } from './routes/_dash/equipe'
import { Route as DashIntegracoesRouteImport } from './routes/_dash/integracoes'
import { Route as DashPavoxAiRouteImport } from './routes/_dash/pavox-ai'
import { Route as DashPlanosRouteImport } from './routes/_dash/planos'
import { Route as DashRecuperacaoRouteImport } from './routes/_dash/recuperacao'
import { Route as DashVendasRouteImport } from './routes/_dash/vendas'
import { Route as PlanosSelecionarRouteImport } from './routes/planos.selecionar'
import { Route as DashCheckoutsIndexRouteImport } from './routes/_dash/checkouts.index'
import { Route as DashCheckoutsIdRouteImport } from './routes/_dash/checkouts.$id'
import { Route as DashCheckoutsNovoRouteImport } from './routes/_dash/checkouts.novo'
import { Route as DashMarketingIndexRouteImport } from './routes/_dash/marketing.index'
import { Route as DashMarketingAbTestingRouteImport } from './routes/_dash/marketing.ab-testing'
import { Route as DashMarketingAutomacaoRouteImport } from './routes/_dash/marketing.automacao'
import { Route as DashMarketingBrindesRouteImport } from './routes/_dash/marketing.brindes'
import { Route as DashMarketingCompraAoVivoRouteImport } from './routes/_dash/marketing.compra-ao-vivo'
import { Route as DashMarketingCuponsRouteImport } from './routes/_dash/marketing.cupons'
import { Route as DashMarketingEscassezRouteImport } from './routes/_dash/marketing.escassez'
import { Route as DashMarketingFaixaDescontoRouteImport } from './routes/_dash/marketing.faixa-desconto'
import { Route as DashMarketingOrderBumpRouteImport } from './routes/_dash/marketing.order-bump'
import { Route as DashMarketingPixelsRouteImport } from './routes/_dash/marketing.pixels'
import { Route as DashMarketingProvasSociaisRouteImport } from './routes/_dash/marketing.provas-sociais'
import { Route as DashMarketingRecuperacaoRouteImport } from './routes/_dash/marketing.recuperacao'
import { Route as DashMarketingSugestoesPagamentoRouteImport } from './routes/_dash/marketing.sugestoes-pagamento'
import { Route as DashMarketingUpsellRouteImport } from './routes/_dash/marketing.upsell'
import { Route as DashPedidosIndexRouteImport } from './routes/_dash/pedidos.index'
import { Route as DashPedidosIdRouteImport } from './routes/_dash/pedidos.$id'
import { Route as DashProdutosIndexRouteImport } from './routes/_dash/produtos.index'
import { Route as DashProdutosIdRouteImport } from './routes/_dash/produtos.$id'
import { Route as DashProdutosNovoRouteImport } from './routes/_dash/produtos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarEmailRoute = ConfirmarEmailRouteImport.update({
  id: '/confirmar-email',
  path: '/confirmar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashAnalyticsRoute = DashAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashRoute,
} as any)
const DashClientesRoute = DashClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashRoute,
} as any)
const DashConfiguracoesRoute = DashConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashRoute,
} as any)
const DashContaRoute = DashContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashDominiosRoute = DashDominiosRouteImport.update({
  id: '/dominios',
  path: '/dominios',
  getParentRoute: () => DashRoute,
} as any)
const DashEquipeRoute = DashEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => DashRoute,
} as any)
const DashIntegracoesRoute = DashIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => DashRoute,
} as any)
const DashPavoxAiRoute = DashPavoxAiRouteImport.update({
  id: '/pavox-ai',
  path: '/pavox-ai',
  getParentRoute: () => DashRoute,
} as any)
const DashPlanosRoute = DashPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => DashRoute,
} as any)
const DashRecuperacaoRoute = DashRecuperacaoRouteImport.update({
  id: '/recuperacao',
  path: '/recuperacao',
  getParentRoute: () => DashRoute,
} as any)
const DashVendasRoute = DashVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => DashRoute,
} as any)
const PlanosSelecionarRoute = PlanosSelecionarRouteImport.update({
  id: '/planos/selecionar',
  path: '/planos/selecionar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashCheckoutsIndexRoute = DashCheckoutsIndexRouteImport.update({
  id: '/checkouts/',
  path: '/checkouts/',
  getParentRoute: () => DashRoute,
} as any)
const DashCheckoutsIdRoute = DashCheckoutsIdRouteImport.update({
  id: '/checkouts/$id',
  path: '/checkouts/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashCheckoutsNovoRoute = DashCheckoutsNovoRouteImport.update({
  id: '/checkouts/novo',
  path: '/checkouts/novo',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketingIndexRoute = DashMarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketingAbTestingRoute = DashMarketingAbTestingRouteImport.update({
  id: '/marketing/ab-testing',
  path: '/marketing/ab-testing',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketingAutomacaoRoute = DashMarketingAutomacaoRouteImport.update({
  id: '/marketing/automacao',
  path: '/marketing/automacao',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketingBrindesRoute = DashMarketingBrindesRouteImport.update({
  id: '/marketing/brindes',
  path: '/marketing/brindes',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketingCompraAoVivoRoute =
  DashMarketingCompraAoVivoRouteImport.update({
    id: '/marketing/compra-ao-vivo',
    path: '/marketing/compra-ao-vivo',
    getParentRoute: () => DashRoute,
  } as any)
const DashMarketingCuponsRoute = DashMarketingCuponsRouteImport.update({
  id: '/marketing/cupons',
  path: '/marketing/cupons',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketingEscassezRoute = DashMarketingEscassezRouteImport.update({
  id: '/marketing/escassez',
  path: '/marketing/escassez',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketingFaixaDescontoRoute =
  DashMarketingFaixaDescontoRouteImport.update({
    id: '/marketing/faixa-desconto',
    path: '/marketing/faixa-desconto',
    getParentRoute: () => DashRoute,
  } as any)
const DashMarketingOrderBumpRoute = DashMarketingOrderBumpRouteImport.update({
  id: '/marketing/order-bump',
  path: '/marketing/order-bump',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketingPixelsRoute = DashMarketingPixelsRouteImport.update({
  id: '/marketing/pixels',
  path: '/marketing/pixels',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketingProvasSociaisRoute =
  DashMarketingProvasSociaisRouteImport.update({
    id: '/marketing/provas-sociais',
    path: '/marketing/provas-sociais',
    getParentRoute: () => DashRoute,
  } as any)
const DashMarketingRecuperacaoRoute =
  DashMarketingRecuperacaoRouteImport.update({
    id: '/marketing/recuperacao',
    path: '/marketing/recuperacao',
    getParentRoute: () => DashRoute,
  } as any)
const DashMarketingSugestoesPagamentoRoute =
  DashMarketingSugestoesPagamentoRouteImport.update({
    id: '/marketing/sugestoes-pagamento',
    path: '/marketing/sugestoes-pagamento',
    getParentRoute: () => DashRoute,
  } as any)
const DashMarketingUpsellRoute = DashMarketingUpsellRouteImport.update({
  id: '/marketing/upsell',
  path: '/marketing/upsell',
  getParentRoute: () => DashRoute,
} as any)
const DashPedidosIndexRoute = DashPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => DashRoute,
} as any)
const DashPedidosIdRoute = DashPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashProdutosIndexRoute = DashProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => DashRoute,
} as any)
const DashProdutosIdRoute = DashProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashProdutosNovoRoute = DashProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/login': typeof LoginRoute
  '/analytics': typeof DashAnalyticsRoute
  '/clientes': typeof DashClientesRoute
  '/configuracoes': typeof DashConfiguracoesRoute
  '/conta': typeof DashContaRoute
  '/dashboard': typeof DashDashboardRoute
  '/dominios': typeof DashDominiosRoute
  '/equipe': typeof DashEquipeRoute
  '/integracoes': typeof DashIntegracoesRoute
  '/pavox-ai': typeof DashPavoxAiRoute
  '/planos': typeof DashPlanosRoute
  '/recuperacao': typeof DashRecuperacaoRoute
  '/vendas': typeof DashVendasRoute
  '/planos/selecionar': typeof PlanosSelecionarRoute
  '/checkouts/$id': typeof DashCheckoutsIdRoute
  '/checkouts/novo': typeof DashCheckoutsNovoRoute
  '/marketing/ab-testing': typeof DashMarketingAbTestingRoute
  '/marketing/automacao': typeof DashMarketingAutomacaoRoute
  '/marketing/brindes': typeof DashMarketingBrindesRoute
  '/marketing/compra-ao-vivo': typeof DashMarketingCompraAoVivoRoute
  '/marketing/cupons': typeof DashMarketingCuponsRoute
  '/marketing/escassez': typeof DashMarketingEscassezRoute
  '/marketing/faixa-desconto': typeof DashMarketingFaixaDescontoRoute
  '/marketing/order-bump': typeof DashMarketingOrderBumpRoute
  '/marketing/pixels': typeof DashMarketingPixelsRoute
  '/marketing/provas-sociais': typeof DashMarketingProvasSociaisRoute
  '/marketing/recuperacao': typeof DashMarketingRecuperacaoRoute
  '/marketing/sugestoes-pagamento': typeof DashMarketingSugestoesPagamentoRoute
  '/marketing/upsell': typeof DashMarketingUpsellRoute
  '/pedidos/$id': typeof DashPedidosIdRoute
  '/produtos/$id': typeof DashProdutosIdRoute
  '/produtos/novo': typeof DashProdutosNovoRoute
  '/checkouts/': typeof DashCheckoutsIndexRoute
  '/marketing/': typeof DashMarketingIndexRoute
  '/pedidos/': typeof DashPedidosIndexRoute
  '/produtos/': typeof DashProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/login': typeof LoginRoute
  '/analytics': typeof DashAnalyticsRoute
  '/clientes': typeof DashClientesRoute
  '/configuracoes': typeof DashConfiguracoesRoute
  '/conta': typeof DashContaRoute
  '/dashboard': typeof DashDashboardRoute
  '/dominios': typeof DashDominiosRoute
  '/equipe': typeof DashEquipeRoute
  '/integracoes': typeof DashIntegracoesRoute
  '/pavox-ai': typeof DashPavoxAiRoute
  '/planos': typeof DashPlanosRoute
  '/recuperacao': typeof DashRecuperacaoRoute
  '/vendas': typeof DashVendasRoute
  '/planos/selecionar': typeof PlanosSelecionarRoute
  '/checkouts/$id': typeof DashCheckoutsIdRoute
  '/checkouts/novo': typeof DashCheckoutsNovoRoute
  '/marketing/ab-testing': typeof DashMarketingAbTestingRoute
  '/marketing/automacao': typeof DashMarketingAutomacaoRoute
  '/marketing/brindes': typeof DashMarketingBrindesRoute
  '/marketing/compra-ao-vivo': typeof DashMarketingCompraAoVivoRoute
  '/marketing/cupons': typeof DashMarketingCuponsRoute
  '/marketing/escassez': typeof DashMarketingEscassezRoute
  '/marketing/faixa-desconto': typeof DashMarketingFaixaDescontoRoute
  '/marketing/order-bump': typeof DashMarketingOrderBumpRoute
  '/marketing/pixels': typeof DashMarketingPixelsRoute
  '/marketing/provas-sociais': typeof DashMarketingProvasSociaisRoute
  '/marketing/recuperacao': typeof DashMarketingRecuperacaoRoute
  '/marketing/sugestoes-pagamento': typeof DashMarketingSugestoesPagamentoRoute
  '/marketing/upsell': typeof DashMarketingUpsellRoute
  '/pedidos/$id': typeof DashPedidosIdRoute
  '/produtos/$id': typeof DashProdutosIdRoute
  '/produtos/novo': typeof DashProdutosNovoRoute
  '/checkouts': typeof DashCheckoutsIndexRoute
  '/marketing': typeof DashMarketingIndexRoute
  '/pedidos': typeof DashPedidosIndexRoute
  '/produtos': typeof DashProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/login': typeof LoginRoute
  '/_dash/analytics': typeof DashAnalyticsRoute
  '/_dash/clientes': typeof DashClientesRoute
  '/_dash/configuracoes': typeof DashConfiguracoesRoute
  '/_dash/conta': typeof DashContaRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/dominios': typeof DashDominiosRoute
  '/_dash/equipe': typeof DashEquipeRoute
  '/_dash/integracoes': typeof DashIntegracoesRoute
  '/_dash/pavox-ai': typeof DashPavoxAiRoute
  '/_dash/planos': typeof DashPlanosRoute
  '/_dash/recuperacao': typeof DashRecuperacaoRoute
  '/_dash/vendas': typeof DashVendasRoute
  '/planos/selecionar': typeof PlanosSelecionarRoute
  '/_dash/checkouts/$id': typeof DashCheckoutsIdRoute
  '/_dash/checkouts/novo': typeof DashCheckoutsNovoRoute
  '/_dash/marketing/ab-testing': typeof DashMarketingAbTestingRoute
  '/_dash/marketing/automacao': typeof DashMarketingAutomacaoRoute
  '/_dash/marketing/brindes': typeof DashMarketingBrindesRoute
  '/_dash/marketing/compra-ao-vivo': typeof DashMarketingCompraAoVivoRoute
  '/_dash/marketing/cupons': typeof DashMarketingCuponsRoute
  '/_dash/marketing/escassez': typeof DashMarketingEscassezRoute
  '/_dash/marketing/faixa-desconto': typeof DashMarketingFaixaDescontoRoute
  '/_dash/marketing/order-bump': typeof DashMarketingOrderBumpRoute
  '/_dash/marketing/pixels': typeof DashMarketingPixelsRoute
  '/_dash/marketing/provas-sociais': typeof DashMarketingProvasSociaisRoute
  '/_dash/marketing/recuperacao': typeof DashMarketingRecuperacaoRoute
  '/_dash/marketing/sugestoes-pagamento': typeof DashMarketingSugestoesPagamentoRoute
  '/_dash/marketing/upsell': typeof DashMarketingUpsellRoute
  '/_dash/pedidos/$id': typeof DashPedidosIdRoute
  '/_dash/produtos/$id': typeof DashProdutosIdRoute
  '/_dash/produtos/novo': typeof DashProdutosNovoRoute
  '/_dash/checkouts/': typeof DashCheckoutsIndexRoute
  '/_dash/marketing/': typeof DashMarketingIndexRoute
  '/_dash/pedidos/': typeof DashPedidosIndexRoute
  '/_dash/produtos/': typeof DashProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/confirmar-email'
    | '/login'
    | '/analytics'
    | '/clientes'
    | '/configuracoes'
    | '/conta'
    | '/dashboard'
    | '/dominios'
    | '/equipe'
    | '/integracoes'
    | '/pavox-ai'
    | '/planos'
    | '/recuperacao'
    | '/vendas'
    | '/planos/selecionar'
    | '/checkouts/$id'
    | '/checkouts/novo'
    | '/marketing/ab-testing'
    | '/marketing/automacao'
    | '/marketing/brindes'
    | '/marketing/compra-ao-vivo'
    | '/marketing/cupons'
    | '/marketing/escassez'
    | '/marketing/faixa-desconto'
    | '/marketing/order-bump'
    | '/marketing/pixels'
    | '/marketing/provas-sociais'
    | '/marketing/recuperacao'
    | '/marketing/sugestoes-pagamento'
    | '/marketing/upsell'
    | '/pedidos/$id'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/checkouts/'
    | '/marketing/'
    | '/pedidos/'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/confirmar-email'
    | '/login'
    | '/analytics'
    | '/clientes'
    | '/configuracoes'
    | '/conta'
    | '/dashboard'
    | '/dominios'
    | '/equipe'
    | '/integracoes'
    | '/pavox-ai'
    | '/planos'
    | '/recuperacao'
    | '/vendas'
    | '/planos/selecionar'
    | '/checkouts/$id'
    | '/checkouts/novo'
    | '/marketing/ab-testing'
    | '/marketing/automacao'
    | '/marketing/brindes'
    | '/marketing/compra-ao-vivo'
    | '/marketing/cupons'
    | '/marketing/escassez'
    | '/marketing/faixa-desconto'
    | '/marketing/order-bump'
    | '/marketing/pixels'
    | '/marketing/provas-sociais'
    | '/marketing/recuperacao'
    | '/marketing/sugestoes-pagamento'
    | '/marketing/upsell'
    | '/pedidos/$id'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/checkouts'
    | '/marketing'
    | '/pedidos'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/cadastro'
    | '/confirmar-email'
    | '/login'
    | '/_dash/analytics'
    | '/_dash/clientes'
    | '/_dash/configuracoes'
    | '/_dash/conta'
    | '/_dash/dashboard'
    | '/_dash/dominios'
    | '/_dash/equipe'
    | '/_dash/integracoes'
    | '/_dash/pavox-ai'
    | '/_dash/planos'
    | '/_dash/recuperacao'
    | '/_dash/vendas'
    | '/planos/selecionar'
    | '/_dash/checkouts/$id'
    | '/_dash/checkouts/novo'
    | '/_dash/marketing/ab-testing'
    | '/_dash/marketing/automacao'
    | '/_dash/marketing/brindes'
    | '/_dash/marketing/compra-ao-vivo'
    | '/_dash/marketing/cupons'
    | '/_dash/marketing/escassez'
    | '/_dash/marketing/faixa-desconto'
    | '/_dash/marketing/order-bump'
    | '/_dash/marketing/pixels'
    | '/_dash/marketing/provas-sociais'
    | '/_dash/marketing/recuperacao'
    | '/_dash/marketing/sugestoes-pagamento'
    | '/_dash/marketing/upsell'
    | '/_dash/pedidos/$id'
    | '/_dash/produtos/$id'
    | '/_dash/produtos/novo'
    | '/_dash/checkouts/'
    | '/_dash/marketing/'
    | '/_dash/pedidos/'
    | '/_dash/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ConfirmarEmailRoute: typeof ConfirmarEmailRoute
  LoginRoute: typeof LoginRoute
  PlanosSelecionarRoute: typeof PlanosSelecionarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-email': {
      id: '/confirmar-email'
      path: '/confirmar-email'
      fullPath: '/confirmar-email'
      preLoaderRoute: typeof ConfirmarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/analytics': {
      id: '/_dash/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashAnalyticsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/clientes': {
      id: '/_dash/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof DashClientesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/configuracoes': {
      id: '/_dash/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof DashConfiguracoesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/conta': {
      id: '/_dash/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof DashContaRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dominios': {
      id: '/_dash/dominios'
      path: '/dominios'
      fullPath: '/dominios'
      preLoaderRoute: typeof DashDominiosRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/equipe': {
      id: '/_dash/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof DashEquipeRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/integracoes': {
      id: '/_dash/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof DashIntegracoesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/pavox-ai': {
      id: '/_dash/pavox-ai'
      path: '/pavox-ai'
      fullPath: '/pavox-ai'
      preLoaderRoute: typeof DashPavoxAiRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/planos': {
      id: '/_dash/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof DashPlanosRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/recuperacao': {
      id: '/_dash/recuperacao'
      path: '/recuperacao'
      fullPath: '/recuperacao'
      preLoaderRoute: typeof DashRecuperacaoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/vendas': {
      id: '/_dash/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof DashVendasRouteImport
      parentRoute: typeof DashRoute
    }
    '/planos/selecionar': {
      id: '/planos/selecionar'
      path: '/planos/selecionar'
      fullPath: '/planos/selecionar'
      preLoaderRoute: typeof PlanosSelecionarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/checkouts/': {
      id: '/_dash/checkouts/'
      path: '/checkouts'
      fullPath: '/checkouts/'
      preLoaderRoute: typeof DashCheckoutsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/checkouts/$id': {
      id: '/_dash/checkouts/$id'
      path: '/checkouts/$id'
      fullPath: '/checkouts/$id'
      preLoaderRoute: typeof DashCheckoutsIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/checkouts/novo': {
      id: '/_dash/checkouts/novo'
      path: '/checkouts/novo'
      fullPath: '/checkouts/novo'
      preLoaderRoute: typeof DashCheckoutsNovoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/': {
      id: '/_dash/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof DashMarketingIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/ab-testing': {
      id: '/_dash/marketing/ab-testing'
      path: '/marketing/ab-testing'
      fullPath: '/marketing/ab-testing'
      preLoaderRoute: typeof DashMarketingAbTestingRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/automacao': {
      id: '/_dash/marketing/automacao'
      path: '/marketing/automacao'
      fullPath: '/marketing/automacao'
      preLoaderRoute: typeof DashMarketingAutomacaoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/brindes': {
      id: '/_dash/marketing/brindes'
      path: '/marketing/brindes'
      fullPath: '/marketing/brindes'
      preLoaderRoute: typeof DashMarketingBrindesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/compra-ao-vivo': {
      id: '/_dash/marketing/compra-ao-vivo'
      path: '/marketing/compra-ao-vivo'
      fullPath: '/marketing/compra-ao-vivo'
      preLoaderRoute: typeof DashMarketingCompraAoVivoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/cupons': {
      id: '/_dash/marketing/cupons'
      path: '/marketing/cupons'
      fullPath: '/marketing/cupons'
      preLoaderRoute: typeof DashMarketingCuponsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/escassez': {
      id: '/_dash/marketing/escassez'
      path: '/marketing/escassez'
      fullPath: '/marketing/escassez'
      preLoaderRoute: typeof DashMarketingEscassezRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/faixa-desconto': {
      id: '/_dash/marketing/faixa-desconto'
      path: '/marketing/faixa-desconto'
      fullPath: '/marketing/faixa-desconto'
      preLoaderRoute: typeof DashMarketingFaixaDescontoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/order-bump': {
      id: '/_dash/marketing/order-bump'
      path: '/marketing/order-bump'
      fullPath: '/marketing/order-bump'
      preLoaderRoute: typeof DashMarketingOrderBumpRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/pixels': {
      id: '/_dash/marketing/pixels'
      path: '/marketing/pixels'
      fullPath: '/marketing/pixels'
      preLoaderRoute: typeof DashMarketingPixelsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/provas-sociais': {
      id: '/_dash/marketing/provas-sociais'
      path: '/marketing/provas-sociais'
      fullPath: '/marketing/provas-sociais'
      preLoaderRoute: typeof DashMarketingProvasSociaisRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/recuperacao': {
      id: '/_dash/marketing/recuperacao'
      path: '/marketing/recuperacao'
      fullPath: '/marketing/recuperacao'
      preLoaderRoute: typeof DashMarketingRecuperacaoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/sugestoes-pagamento': {
      id: '/_dash/marketing/sugestoes-pagamento'
      path: '/marketing/sugestoes-pagamento'
      fullPath: '/marketing/sugestoes-pagamento'
      preLoaderRoute: typeof DashMarketingSugestoesPagamentoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/marketing/upsell': {
      id: '/_dash/marketing/upsell'
      path: '/marketing/upsell'
      fullPath: '/marketing/upsell'
      preLoaderRoute: typeof DashMarketingUpsellRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/pedidos/': {
      id: '/_dash/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof DashPedidosIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/pedidos/$id': {
      id: '/_dash/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof DashPedidosIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/produtos/': {
      id: '/_dash/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof DashProdutosIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/produtos/$id': {
      id: '/_dash/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof DashProdutosIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/produtos/novo': {
      id: '/_dash/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof DashProdutosNovoRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAnalyticsRoute: typeof DashAnalyticsRoute
  DashClientesRoute: typeof DashClientesRoute
  DashConfiguracoesRoute: typeof DashConfiguracoesRoute
  DashContaRoute: typeof DashContaRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashDominiosRoute: typeof DashDominiosRoute
  DashEquipeRoute: typeof DashEquipeRoute
  DashIntegracoesRoute: typeof DashIntegracoesRoute
  DashPavoxAiRoute: typeof DashPavoxAiRoute
  DashPlanosRoute: typeof DashPlanosRoute
  DashRecuperacaoRoute: typeof DashRecuperacaoRoute
  DashVendasRoute: typeof DashVendasRoute
  DashCheckoutsIdRoute: typeof DashCheckoutsIdRoute
  DashCheckoutsNovoRoute: typeof DashCheckoutsNovoRoute
  DashMarketingAbTestingRoute: typeof DashMarketingAbTestingRoute
  DashMarketingAutomacaoRoute: typeof DashMarketingAutomacaoRoute
  DashMarketingBrindesRoute: typeof DashMarketingBrindesRoute
  DashMarketingCompraAoVivoRoute: typeof DashMarketingCompraAoVivoRoute
  DashMarketingCuponsRoute: typeof DashMarketingCuponsRoute
  DashMarketingEscassezRoute: typeof DashMarketingEscassezRoute
  DashMarketingFaixaDescontoRoute: typeof DashMarketingFaixaDescontoRoute
  DashMarketingOrderBumpRoute: typeof DashMarketingOrderBumpRoute
  DashMarketingPixelsRoute: typeof DashMarketingPixelsRoute
  DashMarketingProvasSociaisRoute: typeof DashMarketingProvasSociaisRoute
  DashMarketingRecuperacaoRoute: typeof DashMarketingRecuperacaoRoute
  DashMarketingSugestoesPagamentoRoute: typeof DashMarketingSugestoesPagamentoRoute
  DashMarketingUpsellRoute: typeof DashMarketingUpsellRoute
  DashPedidosIdRoute: typeof DashPedidosIdRoute
  DashProdutosIdRoute: typeof DashProdutosIdRoute
  DashProdutosNovoRoute: typeof DashProdutosNovoRoute
  DashCheckoutsIndexRoute: typeof DashCheckoutsIndexRoute
  DashMarketingIndexRoute: typeof DashMarketingIndexRoute
  DashPedidosIndexRoute: typeof DashPedidosIndexRoute
  DashProdutosIndexRoute: typeof DashProdutosIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAnalyticsRoute: DashAnalyticsRoute,
  DashClientesRoute: DashClientesRoute,
  DashConfiguracoesRoute: DashConfiguracoesRoute,
  DashContaRoute: DashContaRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashDominiosRoute: DashDominiosRoute,
  DashEquipeRoute: DashEquipeRoute,
  DashIntegracoesRoute: DashIntegracoesRoute,
  DashPavoxAiRoute: DashPavoxAiRoute,
  DashPlanosRoute: DashPlanosRoute,
  DashRecuperacaoRoute: DashRecuperacaoRoute,
  DashVendasRoute: DashVendasRoute,
  DashCheckoutsIdRoute: DashCheckoutsIdRoute,
  DashCheckoutsNovoRoute: DashCheckoutsNovoRoute,
  DashMarketingAbTestingRoute: DashMarketingAbTestingRoute,
  DashMarketingAutomacaoRoute: DashMarketingAutomacaoRoute,
  DashMarketingBrindesRoute: DashMarketingBrindesRoute,
  DashMarketingCompraAoVivoRoute: DashMarketingCompraAoVivoRoute,
  DashMarketingCuponsRoute: DashMarketingCuponsRoute,
  DashMarketingEscassezRoute: DashMarketingEscassezRoute,
  DashMarketingFaixaDescontoRoute: DashMarketingFaixaDescontoRoute,
  DashMarketingOrderBumpRoute: DashMarketingOrderBumpRoute,
  DashMarketingPixelsRoute: DashMarketingPixelsRoute,
  DashMarketingProvasSociaisRoute: DashMarketingProvasSociaisRoute,
  DashMarketingRecuperacaoRoute: DashMarketingRecuperacaoRoute,
  DashMarketingSugestoesPagamentoRoute: DashMarketingSugestoesPagamentoRoute,
  DashMarketingUpsellRoute: DashMarketingUpsellRoute,
  DashPedidosIdRoute: DashPedidosIdRoute,
  DashProdutosIdRoute: DashProdutosIdRoute,
  DashProdutosNovoRoute: DashProdutosNovoRoute,
  DashCheckoutsIndexRoute: DashCheckoutsIndexRoute,
  DashMarketingIndexRoute: DashMarketingIndexRoute,
  DashPedidosIndexRoute: DashPedidosIndexRoute,
  DashProdutosIndexRoute: DashProdutosIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ConfirmarEmailRoute: ConfirmarEmailRoute,
  LoginRoute: LoginRoute,
  PlanosSelecionarRoute: PlanosSelecionarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
