/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as DashIndexRouteImport } from './routes/_dash/index'
import { Route as DashAnalyticsRouteImport } from './routes/_dash/analytics'
import { Route as DashClientesRouteImport } from './routes/_dash/clientes'
import { Route as DashContaRouteImport } from './routes/_dash/conta'
import { Route as DashIntegracoesRouteImport } from './routes/_dash/integracoes'
import { Route as DashPavoxAiRouteImport } from './routes/_dash/pavox-ai'
import { Route as DashProdutosRouteImport } from './routes/_dash/produtos'
import { Route as DashRecuperacaoRouteImport } from './routes/_dash/recuperacao'
import { Route as DashVendasRouteImport } from './routes/_dash/vendas'
import { Route as DashCheckoutsIndexRouteImport } from './routes/_dash/checkouts.index'
import { Route as DashCheckoutsNovoRouteImport } from './routes/_dash/checkouts.novo'
import { Route as DashPedidosIndexRouteImport } from './routes/_dash/pedidos.index'
import { Route as DashPedidosIdRouteImport } from './routes/_dash/pedidos.$id'

const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashAnalyticsRoute = DashAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashRoute,
} as any)
const DashClientesRoute = DashClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashRoute,
} as any)
const DashContaRoute = DashContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => DashRoute,
} as any)
const DashIntegracoesRoute = DashIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => DashRoute,
} as any)
const DashPavoxAiRoute = DashPavoxAiRouteImport.update({
  id: '/pavox-ai',
  path: '/pavox-ai',
  getParentRoute: () => DashRoute,
} as any)
const DashProdutosRoute = DashProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DashRoute,
} as any)
const DashRecuperacaoRoute = DashRecuperacaoRouteImport.update({
  id: '/recuperacao',
  path: '/recuperacao',
  getParentRoute: () => DashRoute,
} as any)
const DashVendasRoute = DashVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => DashRoute,
} as any)
const DashCheckoutsIndexRoute = DashCheckoutsIndexRouteImport.update({
  id: '/checkouts/',
  path: '/checkouts/',
  getParentRoute: () => DashRoute,
} as any)
const DashCheckoutsNovoRoute = DashCheckoutsNovoRouteImport.update({
  id: '/checkouts/novo',
  path: '/checkouts/novo',
  getParentRoute: () => DashRoute,
} as any)
const DashPedidosIndexRoute = DashPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => DashRoute,
} as any)
const DashPedidosIdRoute = DashPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashIndexRoute
  '/analytics': typeof DashAnalyticsRoute
  '/clientes': typeof DashClientesRoute
  '/conta': typeof DashContaRoute
  '/integracoes': typeof DashIntegracoesRoute
  '/pavox-ai': typeof DashPavoxAiRoute
  '/produtos': typeof DashProdutosRoute
  '/recuperacao': typeof DashRecuperacaoRoute
  '/vendas': typeof DashVendasRoute
  '/checkouts/novo': typeof DashCheckoutsNovoRoute
  '/pedidos/$id': typeof DashPedidosIdRoute
  '/checkouts/': typeof DashCheckoutsIndexRoute
  '/pedidos/': typeof DashPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof DashAnalyticsRoute
  '/clientes': typeof DashClientesRoute
  '/conta': typeof DashContaRoute
  '/integracoes': typeof DashIntegracoesRoute
  '/pavox-ai': typeof DashPavoxAiRoute
  '/produtos': typeof DashProdutosRoute
  '/recuperacao': typeof DashRecuperacaoRoute
  '/vendas': typeof DashVendasRoute
  '/': typeof DashIndexRoute
  '/checkouts/novo': typeof DashCheckoutsNovoRoute
  '/pedidos/$id': typeof DashPedidosIdRoute
  '/checkouts': typeof DashCheckoutsIndexRoute
  '/pedidos': typeof DashPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteWithChildren
  '/_dash/analytics': typeof DashAnalyticsRoute
  '/_dash/clientes': typeof DashClientesRoute
  '/_dash/conta': typeof DashContaRoute
  '/_dash/integracoes': typeof DashIntegracoesRoute
  '/_dash/pavox-ai': typeof DashPavoxAiRoute
  '/_dash/produtos': typeof DashProdutosRoute
  '/_dash/recuperacao': typeof DashRecuperacaoRoute
  '/_dash/vendas': typeof DashVendasRoute
  '/_dash/': typeof DashIndexRoute
  '/_dash/checkouts/novo': typeof DashCheckoutsNovoRoute
  '/_dash/pedidos/$id': typeof DashPedidosIdRoute
  '/_dash/checkouts/': typeof DashCheckoutsIndexRoute
  '/_dash/pedidos/': typeof DashPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/clientes'
    | '/conta'
    | '/integracoes'
    | '/pavox-ai'
    | '/produtos'
    | '/recuperacao'
    | '/vendas'
    | '/checkouts/novo'
    | '/pedidos/$id'
    | '/checkouts/'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/clientes'
    | '/conta'
    | '/integracoes'
    | '/pavox-ai'
    | '/produtos'
    | '/recuperacao'
    | '/vendas'
    | '/'
    | '/checkouts/novo'
    | '/pedidos/$id'
    | '/checkouts'
    | '/pedidos'
  id:
    | '__root__'
    | '/_dash'
    | '/_dash/analytics'
    | '/_dash/clientes'
    | '/_dash/conta'
    | '/_dash/integracoes'
    | '/_dash/pavox-ai'
    | '/_dash/produtos'
    | '/_dash/recuperacao'
    | '/_dash/vendas'
    | '/_dash/'
    | '/_dash/checkouts/novo'
    | '/_dash/pedidos/$id'
    | '/_dash/checkouts/'
    | '/_dash/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/': {
      id: '/_dash/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/analytics': {
      id: '/_dash/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashAnalyticsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/clientes': {
      id: '/_dash/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof DashClientesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/conta': {
      id: '/_dash/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof DashContaRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/integracoes': {
      id: '/_dash/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof DashIntegracoesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/pavox-ai': {
      id: '/_dash/pavox-ai'
      path: '/pavox-ai'
      fullPath: '/pavox-ai'
      preLoaderRoute: typeof DashPavoxAiRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/produtos': {
      id: '/_dash/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof DashProdutosRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/recuperacao': {
      id: '/_dash/recuperacao'
      path: '/recuperacao'
      fullPath: '/recuperacao'
      preLoaderRoute: typeof DashRecuperacaoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/vendas': {
      id: '/_dash/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof DashVendasRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/checkouts/': {
      id: '/_dash/checkouts/'
      path: '/checkouts'
      fullPath: '/checkouts/'
      preLoaderRoute: typeof DashCheckoutsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/checkouts/novo': {
      id: '/_dash/checkouts/novo'
      path: '/checkouts/novo'
      fullPath: '/checkouts/novo'
      preLoaderRoute: typeof DashCheckoutsNovoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/pedidos/': {
      id: '/_dash/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof DashPedidosIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/pedidos/$id': {
      id: '/_dash/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof DashPedidosIdRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAnalyticsRoute: typeof DashAnalyticsRoute
  DashClientesRoute: typeof DashClientesRoute
  DashContaRoute: typeof DashContaRoute
  DashIntegracoesRoute: typeof DashIntegracoesRoute
  DashPavoxAiRoute: typeof DashPavoxAiRoute
  DashProdutosRoute: typeof DashProdutosRoute
  DashRecuperacaoRoute: typeof DashRecuperacaoRoute
  DashVendasRoute: typeof DashVendasRoute
  DashIndexRoute: typeof DashIndexRoute
  DashCheckoutsNovoRoute: typeof DashCheckoutsNovoRoute
  DashPedidosIdRoute: typeof DashPedidosIdRoute
  DashCheckoutsIndexRoute: typeof DashCheckoutsIndexRoute
  DashPedidosIndexRoute: typeof DashPedidosIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAnalyticsRoute: DashAnalyticsRoute,
  DashClientesRoute: DashClientesRoute,
  DashContaRoute: DashContaRoute,
  DashIntegracoesRoute: DashIntegracoesRoute,
  DashPavoxAiRoute: DashPavoxAiRoute,
  DashProdutosRoute: DashProdutosRoute,
  DashRecuperacaoRoute: DashRecuperacaoRoute,
  DashVendasRoute: DashVendasRoute,
  DashIndexRoute: DashIndexRoute,
  DashCheckoutsNovoRoute: DashCheckoutsNovoRoute,
  DashPedidosIdRoute: DashPedidosIdRoute,
  DashCheckoutsIndexRoute: DashCheckoutsIndexRoute,
  DashPedidosIndexRoute: DashPedidosIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
